#!/bin/sh
#
# archipel - this script starts and stops the archipel daemon
#
# chkconfig:   - 85 15
# description:  Archipel is a XMPP based orchestrator for virtualization
# processname: archipel
# config:      /etc/archipel/archipel.conf
# pidfile:     /var/run/archipel.pid

# Source function library.
. /etc/rc.d/init.d/functions


archipel="/usr/bin/ArchipelServer/runarchipel.py"
prog=$(basename $archipel)
ARCHIPEL_CONF_FILE="/etc/archipel/archipel.conf"
lockfile=/var/lock/subsys/archipel

start() {
    [ -x $archipel ] || exit 5
    #[ -f $NGINX_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon $archipel --config="$ARCHIPEL_CONF_FILE" 2>&1 /dev/null
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    start
}


case "$1" in
    start)
        $1
        ;;
    stop)
        $1
        ;;
    restart)
        $1
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart}"
        exit 2
esac