#!/bin/sh
#
# archipel - this script starts and stops the archipel daemon
#
# chkconfig:   - 85 15
# description:  Archipel is a XMPP based orchestrator for virtualization
# processname: archipel
# config:      /etc/archipel/archipel.conf
# pidfile:     /var/run/archipel.pid

# Source function library.
. /etc/rc.d/init.d/functions


archipel="/usr/bin/ArchipelServer/runarchipel.py"
prog=$(basename $archipel)

ARCHIPEL_CONF_FILE="/etc/archipel/archipel.conf"


lockfile=/var/lock/subsys/archipel

start() {
    [ -x $archipel ] || exit 5
    #[ -f $NGINX_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon $archipel --config="$ARCHIPEL_CONF_FILE" 2>&1 /dev/null
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    #configtest_q || configtest || return 6
    stop
    start
}

reload() {
    #configtest_q || configtest || return 6
    echo -n $"Reloading $prog: "
    killproc $nginx -HUP
    echo
}

rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart|configtest)
        $1
        ;;
    force-reload|upgrade) 
        rh_status_q || exit 7
        upgrade
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    status|status_q)
        rh_$1
        ;;
    condrestart|try-restart)
        rh_status_q || exit 7
        restart
	    ;;
    *)
        echo $"Usage: $0 {start|stop|reload|configtest|status|force-reload|upgrade|restart}"
        exit 2
esac