#!/usr/bin/python
# 
# bootstrap
# 
# Copyright (C) 2010 Antoine Mercadal <antoine.mercadal@inframonde.eu>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, sys, getopt
import uuid

MSG_ARCHIPEL_WELCOME = """\
###############################################################################
#                                                                             #
#                                Archipel                                     #
#                                                                             #
###############################################################################

Copyright (C) 2010 Antoine Mercadal <antoine.mercadal@inframonde.eu>
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version. For more information
about the licence see <http://www.gnu.org/licenses/>

Welcome to the installation script of Archipel. Installation is automatic and 
default values should be ok most of the time.

"""


MSG_ARCHIPEL_END = """\
###############################################################################
#                                                                             #
#                                Archipel                                     #
#                                                                             #
###############################################################################

All the requested operation have been executed. If you need more help, please
visit the folowing : 
 * Main project page : http://archipelproject.org
 * Wiki              : https://github.com/primalmotion/Archipel/wiki
 * IRC channel       : irc://freenode.net/#archipel
 * Twitter           : http://twitter.com/ArchipelProject

If you find any bug, please tell us using our tracker :
 * Official tracker  : https://github.org/primalmotion/Archipel/issues

"""


def ask(message, answers=None, default=None):
    question = " * " + message
    if answers and default:
        question += " ["
        for a in answers:
            a = a
            if default and a in (default): a = "\033[32m" + a + "\033[0m"
            question += a + "/"
        question = question[:-1]
        question += "]"
        
    if not answers and default:
        question += " [\033[32m" + default + "\033[0m]"
        
    question += " : "
    
    resp = raw_input(question)
    
    if default:
        if resp == "": resp = default;
    
    if answers and default:
        if not resp in answers and len(answers) > 0:
            resp = ask("\033[33mYou must select of the following answer\033[0m", answers, default);
    
    return resp


def ask_bool(message, default="y"):
    if ask(message, ["y", "n"], default) == "y":
        return True
    return False


def test_user_root():
    import getpass
    if not getpass.getuser() == "root":
        print "\033[31m\n * ERROR: You need to be root\033[0m\n"
        sys.exit(1)



### tests / init / Utils

def test_cmd(cmd):
    if os.system("which %s > /dev/null 2>&1" % cmd) != 0:
        return False
    return True


def test_cmd_or_die(cmd, warn=False):
    if not test_cmd(cmd):
        if not warn:
            print "\033[31m\n * ERROR: You need %s\033[0m\n" % cmd
            sys.exit(1)
        else:
            print "\033[33m   - WARNING: You'll need %s to use certains features.\033[0m" % cmd


def test_basic_cmds():
    test_cmd_or_die("git")
    test_cmd_or_die("cp")
    test_cmd_or_die("mkdir")
    test_cmd_or_die("mv")
    test_cmd_or_die("echo")
    test_cmd_or_die("chmod")
    test_cmd_or_die("chown")


def clear():
    os.system("clear")



### install client
def install_archipelclient():
    os.system("cd ./ArchipelClient && ./bootstrap")


### install agent
def install_archipelagent():
    os.system("cd ./ArchipelAgent && python setup.py install")



### Main

def main():
    try:
        clear()
        
        print MSG_ARCHIPEL_WELCOME
        
        test_user_root()
        
        install_agent = ask_bool("Would you like to install Archipel Agent ?")
        install_client = ask_bool("Would you like to install Archipel Client ?")
        
        print "\n\nWe will now execute the following installation: "
        if install_agent: print " - Archipel Agent"
        if install_client: print " - Archipel Client"
        
        print " "
        
        confirm = ask("Do you confirm ?", ["y", "n"], "y")
        if confirm == "n":
            print " \033[33m* Installation canceled by user\033[0m"
            sys.exit(0)
        
        if install_agent: install_archipelagent()
        if install_client: install_archipelclient()
        
        clear()
        
        print MSG_ARCHIPEL_END;
    except KeyboardInterrupt:
        print "\n\n\033[33m * Installation canceled by user\033[0m\n"




if __name__ == "__main__":
    main()
