/*  
 * Jakefile
 *    
 * Copyright (C) 2010 Antoine Mercadal <antoine.mercadal@inframonde.eu>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* enter the following information about you and your module */ 
var AUTHOR		= "Antoine Mercadal";
var EMAIL		= "feedback @nospam@ yourcompany.com";
var COMPANY		= "org.archipelproject";
var NAME 		= "VirtualMachineSnapshots";
var SUMMARY		= "Modules for screenshoting";
var VERSION		= "1.0";




/* YOU SHOULD NOT HAVE TO CHANGE THE FOLLOWING */
var ENV = require("system").env,
    FILE = require("file"),
    task = require("jake").task,
    FileList = require("jake").FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("buildmodule", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", NAME + ".build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName(NAME);
    task.setIdentifier( COMPANY + "." + NAME);
    task.setVersion(VERSION);
    task.setAuthor(AUTHOR);
    task.setEmail(EMAIL);
    task.setSummary(SUMMARY);
    task.setSources(new FileList("*.j"));
    task.setResources(new FileList("Resources/*"));
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("default", ["buildmodule"]);
