/*
 * Jakefile
 * Archipel
 *
 * Created by You on February 11, 2010.
 * Copyright 2010, Your Company All rights reserved.
 */

var ENV = require("system").env,
    FILE = require("file"),
	OS = require("os"),
    task = require("jake").task,
    FileList = require("jake").FileList,
    app = require("cappuccino/jake").app,
    configuration = ENV["CONFIG"] || ENV["CONFIGURATION"] || ENV["c"] || "Debug";

app ("Archipel", function(task)
{
    task.setBuildIntermediatesPath(FILE.join("Build", "Archipel.build", configuration));
    task.setBuildPath(FILE.join("Build", configuration));

    task.setProductName("Archipel");
    task.setIdentifier("fr.antoinemercadal.Archipel");
    task.setVersion("1.0");
    task.setAuthor("Antoine Mercadal");
    task.setEmail("antoine.mercadal @nospam@ inframonde.eu");
    task.setSummary("Archipel");
    task.setSources(new FileList("*.j"));
    task.setResources(new FileList("Resources/*"));
    task.setIndexFilePath("index.html");
    task.setInfoPlistPath("Info.plist");

    if (configuration === "Debug")
        task.setCompilerFlags("-DDEBUG -g");
    else
        task.setCompilerFlags("-O");
});

task ("documentation", function(task)
{
   OS.system("doxygen Archipel.doxygen")
});

task ("default", ["Archipel"]);
task ("docs", ["documentation"]);
task ("all", ["Archipel", "documentation"]);