
@interface TNVirtualMachineDefinitionController : TNModule
{
    IBOutlet NSButton* buttonClocks;
    IBOutlet NSButton* buttonDefine;
    IBOutlet NSButton* buttonDomainType;
    IBOutlet NSButton* buttonOnCrash;
    IBOutlet NSButton* buttonOnPowerOff;
    IBOutlet NSButton* buttonOnReboot;
    IBOutlet NSButton* buttonUndefine;
    IBOutlet NSButton* buttonXMLEditor;
    IBOutlet CPButtonBar* buttonBarControlDrives;
    IBOutlet CPButtonBar* buttonBarControlNics;
    IBOutlet NSPopUpButton* buttonBoot;
    IBOutlet NSPopUpButton* buttonGuests;
    IBOutlet NSPopUpButton* buttonInputType;
    IBOutlet NSPopUpButton* buttonMachines;
    IBOutlet NSPopUpButton* buttonPreferencesBoot;
    IBOutlet NSPopUpButton* buttonPreferencesClockOffset;
    IBOutlet NSPopUpButton* buttonPreferencesDriveCache;
    IBOutlet NSPopUpButton* buttonPreferencesInput;
    IBOutlet NSPopUpButton* buttonPreferencesNumberOfCPUs;
    IBOutlet NSPopUpButton* buttonPreferencesOnCrash;
    IBOutlet NSPopUpButton* buttonPreferencesOnPowerOff;
    IBOutlet NSPopUpButton* buttonPreferencesOnReboot;
    IBOutlet NSPopUpButton* buttonPreferencesVNCKeyMap;
    IBOutlet NSPopUpButton* buttonVNCKeymap;
    IBOutlet NSSearchField* fieldFilterDrives;
    IBOutlet NSSearchField* fieldFilterNics;
    IBOutlet NSTabView* tabViewDevices;
    IBOutlet NSTextField* fieldMemory;
    IBOutlet NSTextField* fieldPreferencesDomainType;
    IBOutlet NSTextField* fieldPreferencesGuest;
    IBOutlet NSTextField* fieldPreferencesMachine;
    IBOutlet NSTextField* fieldPreferencesMemory;
    IBOutlet NSTextField* fieldVNCPassword;
    IBOutlet NSView* maskingView;
    IBOutlet NSView* viewBottomControl;
    IBOutlet NSView* viewDeviceVirtualDrives;
    IBOutlet NSView* viewDeviceVirtualNics;
    IBOutlet NSView* viewDrivesContainer;
    IBOutlet NSView* viewMainContent;
    IBOutlet NSView* viewNicsContainer;
    IBOutlet NSWindow* windowXMLEditor;
    IBOutlet LPMultiLineTextField* fieldStringXMLDesc;
    IBOutlet TNDriveController* driveController;
    IBOutlet TNNetworkController* networkController;
    IBOutlet TNSwitch* switchACPI;
    IBOutlet TNSwitch* switchAPIC;
    IBOutlet TNSwitch* switchHugePages;
    IBOutlet TNSwitch* switchPAE;
    IBOutlet TNSwitch* switchPreferencesHugePages;
    IBOutlet TNTextFieldStepper* stepperNumberCPUs;
    IBOutlet TNUIKitScrollView* scrollViewContentView;
    IBOutlet TNUIKitScrollView* scrollViewForDrives;
    IBOutlet TNUIKitScrollView* scrollViewForNics;
}
- (IBAction)openXMLEditor:(id)aSender;
- (IBAction)makeDefinitionEdited:(id)aSender;
- (IBAction)defineXML:(id)aSender;
- (IBAction)defineXMLString:(id)aSender;
- (IBAction)undefineXML:(id)aSender;
- (IBAction)addNetworkCard:(id)aSender;
- (IBAction)editNetworkCard:(id)aSender;
- (IBAction)deleteNetworkCard:(id)aSender;
- (IBAction)addDrive:(id)aSender;
- (IBAction)editDrive:(id)aSender;
- (IBAction)deleteDrive:(id)aSender;
- (IBAction)buildGUIAccordingToCurrentGuest:(id)aSender;
- (IBAction)updateMachinesAccordingToDomainType:(id)aSender;
@end