#!/bin/bash

# A POSIX variable
OPTIND=1         # Reset in case getopts has been used previously in the shell.

# Initialize our own variables:
output_file=""
verbose=0

function show_help {
    echo "archipel-central-server is a helper script to set up a central server for archipel.\
Syntax : archipel-central-server command -param"
}

function initialize_ejabberd {
    echo "(Re)initializing ejabberd"
    service ejabberd stop
    echo "purgin ejabberd db"
    rm -rvf /var/lib/ejabberd/*


    service ejabberd start
    ejabberdctl register admin archipel-test.archipel.priv admin
    # create archipel pubsubs
    archipel-centralagentnode -j admin@$(hostname) -p admin -c
    archipel-adminaccounts -j admin@$(hostname) -p admin -c
    archipel-tagnode -j admin@$(hostname) -p admin -c
    archipel-rolesnode -j admin@$(hostname) -p admin -c
    ejabberdctl register professeur $(hostname) professeur
    archipel-adminaccounts -j admin@$(hostname) -p admin -a professeur@$(hostname)
}

while getopts "h?vf:" opt; do
    case "$opt" in
    h|\?)
        show_help
        exit 0
        ;;
    f)  output_file=$OPTARG
        ;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

script_command=$@

if [ "$script_command" == "install" ] 
then
    echo "now installing central server"
    sed -e "s/FQDN/archipel-test.archipel.priv/" /etc/ejabberd/ejabberd.cfg.template > /etc/ejabberd/ejabberd.cfg
    service ejabberd stop
    echo "installing xmlrpc beam"
    svn checkout http://svn.process-one.net/ejabberd-modules/
    cd /usr/local/src/ejabberd-modules/ejabberd_xmlrpc/trunk
    ./build.sh
    cp ebin/ejabberd_xmlrpc.beam  /usr/lib64/ejabberd/ebin/

    initialize_ejabberd

    # mount developer env
    mkdir /archipel_dev/
    mount -t cifs -o user=smbuser,password=archipel //192.168.137.1/archipel /archipel_dev
    cd /archipel_dev/ArchipelAgent/

    # developer mode only
    ./buildCentralAgent -d
    easy_install sqlalchemy
    archipel-central-agent-initinstall -x $(hostname)
    chkconfig archipel-central-agent on
    # configure central agent log to where other logs are
    sed -i 's&logging_file_path.*=.*&logging_file_path=/stateless/logs/archipel.archipel-central-server.archipel.priv.log&' /etc/archipel/archipel-central-agent.conf

    # tftp config
    # selinux fix
    restorecon -r /tftpboot

    # samba config
    useradd -M smbuser
    (echo archipel; echo archipel) | smbpasswd -s smbuser
    chown -R smbuser /stateless/
    chgrp -R smbuser /stateless/
    #selinux fix
    chcon -t samba_share_t /stateless/
elif [ "$script_command" == "initialize" ]
then
    initialize_ejabberd
    echo "archipel central server reinitialized"
fi

# End of file
