/*  
 * Jakefile
 *    
 * Copyright (C) 2010 Antoine Mercadal <antoine.mercadal@inframonde.eu>
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/* enter the following information about you and your module */ 
AUTHOR		= "Antoine Mercadal";
EMAIL		= "feedback @nospam@ yourcompany.com";
COMPANY		= "org.archipelproject";
NAME 		= "SampleTabModule";
SUMMARY		= "A short description of your module";
VERSION		= "1.0";

require("../modulescommon.jake")