
@interface AppController : NSObject
{
    IBOutlet CPButtonBar* buttonBarLeft;
    IBOutlet NSImageView* ledIn;
    IBOutlet NSImageView* ledOut;
    IBOutlet NSProgressIndicator* progressIndicatorModulesLoading;
    IBOutlet NSSplitView* splitViewHorizontalRoster;
    IBOutlet NSSplitView* splitViewMain;
    IBOutlet NSSplitView* splitViewTagsContents;
    IBOutlet NSTextField* labelCurrentUser;
    IBOutlet NSTextField* textFieldAboutVersion;
    IBOutlet NSView* filterView;
    IBOutlet NSView* hintView;
    IBOutlet NSView* rightView;
    IBOutlet NSView* statusBar;
    IBOutlet CPWebView* helpView;
    IBOutlet CPWebView* webViewAboutCredits;
    IBOutlet NSWindow* theWindow;
    IBOutlet NSWindow* windowAboutArchipel;
    IBOutlet TNAvatarController* avatarController;
    IBOutlet TNConnectionController* connectionController;
    IBOutlet TNContactsController* contactsController;
    IBOutlet TNFlipView* leftView;
    IBOutlet TNGroupsController* groupsController;
    IBOutlet TNModuleController* moduleController;
    IBOutlet TNPreferencesController* preferencesController;
    IBOutlet TNPropertiesController* propertiesController;
    IBOutlet TNSearchField* filterField;
    IBOutlet TNTagsController* tagsController;
    IBOutlet TNUpdateController* updateController;
    IBOutlet TNUserAvatarController* userAvatarController;
    IBOutlet NSView* viewRosterMask;
}
- (IBAction)toogleRemoveEntity:(id)aSender;
- (IBAction)toggleShowPropertiesView:(id)aSender;
- (IBAction)logout:(id)aSender;
- (IBAction)addContact:(id)aSender;
- (IBAction)deleteContact:(id)aSender;
- (IBAction)addGroup:(id)aSender;
- (IBAction)deleteGroup:(id)aSender;
- (IBAction)selectNextEntity:(id)aSender;
- (IBAction)selectPreviousEntity:(id)aSender;
- (IBAction)renameContact:(id)aSender;
- (IBAction)renameGroup:(id)aSender;
- (IBAction)focusFilter:(id)aSender;
- (IBAction)expandGroup:(id)aSender;
- (IBAction)collapseGroup:(id)aSender;
- (IBAction)expandAllGroups:(id)aSender;
- (IBAction)collapseAllGroups:(id)aSender;
- (IBAction)openWebsite:(id)aSender;
- (IBAction)openWiki:(id)aSender;
- (IBAction)openReleaseNotes:(id)aSender;
- (IBAction)openDonationPage:(id)aSender;
- (IBAction)openBugTracker:(id)aSender;
- (IBAction)switchMainMenu:(id)aSender;
- (IBAction)showAboutWindow:(id)aSender;
- (IBAction)showPreferencesWindow:(id)aSender;
- (IBAction)toolbarItemHelpClick:(id)aSender;
- (IBAction)toolbarItemPresenceStatusClick:(id)aSender;
- (IBAction)toolbarItemLogoutClick:(id)aSender;
- (IBAction)toolbarItemTagsClick:(id)aSender;
- (IBAction)toolbarItemAvatarClick:(id)aSender;
@end